spring.jpa.show-sql=false

logging.level.com.planejamais=INFO
logging.level.org.springframework.web=WARN

springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false

management.endpoint.health.show-details=never

auth.cookie.secure=true
auth.cookie.same-site=Strict
