CREATE TABLE assunto_descricoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assunto_id BIGINT NOT NULL REFERENCES assuntos(id) ON DELETE CASCADE,
    texto TEXT NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_assunto_descricoes_assunto_id ON assunto_descricoes(assunto_id);

INSERT INTO assunto_descricoes (assunto_id, texto, sort_order)
SELECT id, descricao, 0
FROM assuntos
WHERE descricao IS NOT NULL AND TRIM(descricao) <> '';

ALTER TABLE assuntos DROP COLUMN descricao;
